import type { Lesson } from '../../types/curriculum';

export const cicdLessons: Lesson[] = [
  {
    id: 'ci_0',
    title: 'CI/CD: The Automation Engine',
    badge: 'Foundations',
    badgeClass: 'badge-concept',
    content: [
      '**CI/CD** is the backbone of modern software engineering. **Continuous Integration (CI)** means your code is automatically built and tested every time you push to GitHub, ensuring that new changes don\'t break existing features.',
      '**Continuous Deployment (CD)** takes it a step further: if the tests pass, the code is automatically deployed to your production servers. This eliminates human error and ensures that your users always have the latest, most secure version of your app.',
      'The goal is to make "Shipping Code" a boring, routine event. By automating the mechanical tasks of building, testing, and deploying, you free up your team to focus on what matters: solving problems and building features.'
    ],
    code: `// ── The CI/CD Pipeline ──
// 1. PUSH: Developer pushes code to GitHub
// 2. BUILD: Automated server installs deps
// 3. TEST: Runs Vitest/Playwright
// 4. LINT: Checks style and security
// 5. DEPLOY: Push to AWS/Heroku/Railway`
  },
  {
    id: 'ci_1',
    title: 'GitHub Actions: Your First Workflow',
    badge: 'Core',
    badgeClass: 'badge-concept',
    content: [
      '**GitHub Actions** allows you to automate your workflow directly in your repository using YAML files. It uses "Runners" (virtual machines) to execute your commands on every `git push` or `pull request`.',
      'The anatomy of a workflow: A **Trigger** (like `on: push`), a **Job** (a task), and **Steps** (individual commands). GitHub provides an "Actions Marketplace" where you can find pre-built steps for things like setting up Node.js or logging into AWS.',
      'The power of "Self-Correction": If your linting or tests fail in the CI pipeline, GitHub will block you from merging your code into the "main" branch. This provides an automated "Guardrail" that maintains the quality of your codebase.'
    ],
    code: `# ── .github/workflows/main.yml ──
name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm test`
  },
  {
    id: 'ci_2',
    title: 'Build Artifacts & Caching',
    badge: 'Performance',
    badgeClass: 'badge-practice',
    content: [
      'GitHub Actions can be slow if you reinstall all your dependencies from scratch on every push. **Caching** allows you to "save" your `node_modules` folder between runs. If your `package-lock.json` doesn\'t change, the CI will skip the install step.',
      '**Artifacts** are the files generated by your build (like your compiled `dist` folder or a test coverage report). You can "upload" these artifacts so that other jobs (like the Deploy job) can use them, or so you can download them later for debugging.',
      'Understanding the difference between a "Temporary Run" and an "Artifact" is key to efficient CI. You only save what you need. This keeps your pipeline fast and avoids wasting expensive CI/CD minutes provided by your hosting platform.'
    ],
    code: `# ── Caching dependencies in GHA ──
- uses: actions/setup-node@v3
  with:
    node-version: 18
    cache: 'npm' # 👈 Automatically caches node_modules

# ── Saving Build Artifacts ──
- name: Save Build
  uses: actions/upload-artifact@v3
  with:
    name: build-assets
    path: dist/`
  },
  {
    id: 'ci_3',
    title: 'Secrets Management & Env Vars',
    badge: 'Security',
    badgeClass: 'badge-concept',
    content: [
      'Your CI/CD pipeline needs access to sensitive data (like your API keys or database passwords) to deploy your app. **Never hardcode these in your YAML files.** Instead, you use **GitHub Secrets**.',
      'Secrets are encrypted and can only be used by authorized workflows. Even the person who created the secret cannot see it once it\'s saved. You inject them into your workflow using the `${{ secrets.NAME }}` syntax.',
      'Different environments, different secrets: You should have separate secrets for "Staging" and "Production". This ensures that even if a developer has access to the staging environment, they cannot accidentally break or leak data from the production server.'
    ],
    code: `# ── Using Secrets in a job ──
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: npm run build
      - run: railway up
        env:
          # Injected at runtime - never committed!
          RAILWAY_TOKEN: \${{ secrets.RAILWAY_PROD_TOKEN }}`
  },
  {
    id: 'ci_4',
    title: 'Docker in CI: The Golden Image',
    badge: 'Architecture',
    badgeClass: 'badge-practice',
    content: [
      'Running `npm run build` directly in the CI runner can lead to "It works in CI but not on the server" bugs. The solution is to **Build the Docker Image in CI**. This ensures the exact same environment is used for testing and production.',
      'In a professional pipeline, the CI job builds a Docker image, tags it with the unique git commit ID, and pushes it to a "Container Registry" (like GitHub Container Registry or AWS ECR).',
      'The Deploy job then tells your production server: "Pull the image named `my-api:v1.2.3` and start it". This makes rollbacks incredibly easy — if there\'s a bug, you just tell the server to pull the previous version\'s image instead.'
    ],
    code: `# ── Push Docker Image to GHCR ──
- name: Build and Push
  uses: docker/build-push-action@v3
  with:
    push: true
    tags: ghcr.io/user/repo:latest, ghcr.io/user/repo:\${{ github.sha }}`
  },
  {
    id: 'ci_5',
    title: 'Workflow Orchestration: Matrices',
    badge: 'Industry Standard',
    badgeClass: 'badge-code',
    content: [
      'What if your app needs to work on Node 16, 18, and 20? Instead of writing three workflows, you use a **Matrix**. One single YAML file can trigger multiple parallel runs with different configurations.',
      'Matrices allow you to "Stress Test" your software across different operating systems (Windows, Mac, Linux) and runtime versions simultaneously. This is essential for open-source libraries that must work for everyone.',
      '**Fail-Fast Strategy**: By default, if one part of the matrix fails, GitHub cancels the other runs. This saves you money and time. You can disable this if you want to see exactly which versions are failing even if one has already dyed.'
    ],
    code: `# ── Test on multiple Node versions ──
jobs:
  test:
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        os: [ubuntu-latest, windows-latest]
    
    runs-on: \${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: \${{ matrix.node-version }}`
  },
  {
    id: 'ci_6',
    title: 'Infrastructure as Code (IaC) in CD',
    badge: 'Advanced',
    badgeClass: 'badge-code',
    content: [
      'Continuous Deployment isn\'t just about code; it\'s about your **Server Infrastructure**. Tools like **Terraform** or **Pulumi** allow you to define your servers, databases, and networks in version-controlled files (IaC).',
      'In your CD pipeline, you can run `terraform apply`. This automatically creates or updates your cloud resources to match your files. If you add a new database to your project, the CD pipeline will physically create it in AWS for you.',
      'This is "GitOps": the state of your infrastructure is defined by the state of your git repository. No more manual clicking in the AWS console; if it\'s not in the code, it doesn\'t exist in production.'
    ],
    code: `# ── CD Job: Infrastructure Update ──
- name: Terraform Apply
  run: terraform apply -auto-approve
  env:
    AWS_ACCESS_KEY_ID: \${{ secrets.AWS_KEY }}
    AWS_SECRET_ACCESS_KEY: \${{ secrets.AWS_SECRET }}`
  },
  {
    id: 'ci_7',
    title: 'Project Execution: The Automated Ship',
    badge: 'Project',
    badgeClass: 'badge-practice',
    content: [
      'In this final task, you will build the automated engine for JobTrackr. You will create a GitHub Workflow that triggers on every pull request, runs the Vitest and Playwright suites, and if successful, builds a Docker image and pushes it to Railway.',
      'The goal is 100% automation. You must also implement "Automated Staging": every PR should deploy to a temporary "Preview" URL so that the team can test your changes in a real environment before merging to main.',
      '**Studio Task**: Build the "Shipwright" manifest. It should use environment-specific secrets, implement dependency caching, and post the deployment URL as a comment on the GitHub pull request.'
    ],
    code: `# ── Final Ship Checklist ──
# 1. Workflow triggered on PR? [Yes]
# 2. Secrets used for tokens?  [Yes]
# 3. Docker image tagged?      [Yes]
# 4. Cleanup on merge?         [Yes]`
  }
];
